### ISSUE TITLE
ele element is missed

### ISSUE THREAD

**Issue by tonylu880042** [kb0/dart-gpx#15]
Please ignore this

**Comment by HugoHeneault** [comment]
You can close if it's ok for you :)

**Comment by elliotnash** [comment]
> Please ignore this

The ele element also seems to be missed for me in a Trkseg's Wpt, what did you do to get the elevation?

I noticed my trkpt's in the gpx file look like this ```<trkpt ele="162.0" lat="45.527366" lon="-122.728104"/>``` where the ele is an attribute not a child of the trkpt, unlike the gpx files in the examples
