### ISSUE TITLE
Update xml dependency to 6.0.1

### ISSUE THREAD

**Issue by JulianBissekkou** [kb0/dart-gpx#20]
It would be nice if we could update the xml dependency to 6.0.1.
Is there a reason not to do it?

I would love to contribute and create a PR for this.

**Comment by kb0** [comment]
merged

**Comment by JulianBissekkou** [comment]
Did you also publish a new version to pub?

**Comment by kb0** [comment]
yes, version 2.2.0 - https://pub.dev/packages/gpx
