### ISSUE TITLE
Failing GPX file

### ISSUE THREAD

**Issue by moovida** [kb0/dart-gpx#4]
Hello, I was trying to load this gox file: http://speleotrove.com/mapgazer/files/20160617-La-Hermida-to-Bejes.gpx
but the ```GpxReader().fromString(xml);``` throws an exception and I am not able to get the issue out of it.

Any idea what the issue might be?

BTW: thanks for this great project :-)

**Comment by kb0** [comment]
Hi, it's problem with `<fix>` tag. I publish new version 1.1.0 with appropriate reading and writing for  `<fix>` tag

**Comment by moovida** [comment]
Fantastic, thank you.
