### ISSUE TITLE
Save GPX file and upload to Strava

### ISSUE THREAD

**Issue by ilhamamirullah** [kb0/dart-gpx#7]
Hello,

Kindly need your help how to save a file GPX because I wanna write the GPX file then upload to Strava. Is this library support to Strava?

Thank you

**Comment by kb0** [comment]
Hi,

Yes, you can upload GPX generated by this library to Strava. Use `GpxWriter().asString(gpx, pretty: true);` to save your data as GPX string

```
import 'package:gpx/gpx.dart';

main() {
  // create gpx object
  var gpx = Gpx();
  gpx.creator = "dart-gpx library";
  // put your data here
  gpx.wpts = [
    Wpt(lat: 36.62, lon: 101.77, ele: 10.0, name: 'Xining', desc: 'China'),
  ];

  // generate GPX string
  var gpxString = GpxWriter().asString(gpx, pretty: true);

  // save it to file
```

**Comment by Theunodb** [comment]
> Hi,
> 
> Yes, you can upload GPX generated by this library to Strava. Use `GpxWriter().asString(gpx, pretty: true);` to save your data as GPX string
> 
> ```
> import 'package:gpx/gpx.dart';
> 
> main() {
>   // create gpx object
>   var gpx = Gpx();
>   gpx.creator = "dart-gpx library";
>   // put your data here
>   gpx.wpts = [
>     Wpt(lat: 36.62, lon: 101.77, ele: 10.0, name: 'Xining', desc: 'China'),
>   ];
> 
>   // generate GPX string
>   var gpxString = GpxWriter().asString(gpx, pretty: true);
> 
>   // save it to file
> ```

final directory = await getApplicationDocumentsDirectory();
    File file = File('${directory.path}/gpx.gpx');
    await file.writeAsString(gpxString);

    Share.shareXFiles([XFile(file.path)]);
