### ISSUE TITLE
XML 5

### ISSUE THREAD

**Issue by MrCube72** [kb0/dart-gpx#9]
Please, give us an update, that allows XML 5.0.0!!!

**Comment by MrCube72** [comment]
Because gpx 1.1.1 depends on xml ^4.3.0 and no versions of gpx match >1.1.1 <2.0.0, gpx ^1.1.1 requires xml ^4.3.0.
So, because opc depends on both gpx ^1.1.1 and xml ^5.0.0, version solving failed.
pub get failed (1; So, because opc depends on both gpx ^1.1.1 and xml ^5.0.0, version solving failed.)

**Comment by kb0** [comment]
Update dependencies during migration on null safety - v2.0.0 (dart sdk >=2.12.0) - #11
